Repository For-Hives/formenu-front, pull requests merged in 2023-07, with the labels that each got.

#105 Création page blog
  .gitignore
  lib/pocketbase.js
  next.config.js
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/Card.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Loader.jsx
  src/components/SocialIcons.jsx
  src/components/blog/ArrowRightIcon.jsx
  src/components/blog/Article.jsx
  src/components/blog/BriefcaseIcon.jsx
  src/components/blog/MailIcon.jsx
  src/components/blog/Newsletter.jsx
  src/components/blog/Photos.jsx
  src/components/blog/Resume.jsx
  src/components/blog/SocialLink.jsx
  src/images/photos/image-1.jpg
  src/images/photos/image-2.jpg
  src/images/photos/image-3.jpg
  src/images/photos/image-4.jpg
  src/images/photos/image-5.jpg
  src/lib/formatDate.js
  src/lib/getAllArticles.js
  src/pages/_app.jsx
  src/pages/blog.jsx
  src/pages/blog/[slug].jsx
  src/pages/index.jsx
  src/pages/programme-dapport-daffaires.jsx
  src/utils/utils.js
Labels: enhancement, internship

#115 fix link
  src/components/Footer.jsx
  src/components/Header.jsx
Labels: bug

#133 Feat[#127]: fix images
  public/food.png
  public/food_2.png
  public/food_3.png
  public/food_4.png
  public/food_5.png
  src/components/blog/Photos.jsx
Labels: enhancement
